import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  documentacion: [
    "intro",
    "arquitectura",
    "componentes-y-licencias",
    "laboratorio",
    "seguridad",
    "ciclo-de-vida-y-soporte",
    {
      type: "category",
      label: "API de la Consola",
      link: { type: "doc", id: "api-consola" },
      collapsed: true,
      // Páginas generadas desde apps/console-api/openapi.yaml (scripts/gen-api-docs.mjs).
      items: [{ type: "autogenerated", dirName: "referencia-api" }],
    },
    "hoja-de-ruta",
    "licencia-y-avisos",
  ],
};

export default sidebars;
