import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  documentacion: [
    "intro",
    "arquitectura",
    "componentes-y-licencias",
    "laboratorio",
    {
      type: "category",
      label: "Instalación",
      link: { type: "doc", id: "instalacion/index" },
      collapsed: true,
      items: ["instalacion/cpd-rke2", "instalacion/gcp-gke", "instalacion/valores-por-ambiente"],
    },
    "seguridad",
    "ciclo-de-vida-y-soporte",
    {
      type: "category",
      label: "Operación",
      collapsed: false,
      items: ["operacion/respaldo-y-restauracion"],
    },
    {
      type: "category",
      label: "Capacitación",
      link: { type: "doc", id: "capacitacion/index" },
      collapsed: true,
      items: [
        "capacitacion/laboratorio-participante",
        "capacitacion/m0-induccion",
        "capacitacion/m1-instalacion",
        "capacitacion/m2-administracion",
        "capacitacion/m3-apis",
        "capacitacion/m4-integracion",
        "capacitacion/m5-seguridad",
        "capacitacion/m6-operacion",
        "capacitacion/m7-evaluacion",
        "capacitacion/certificacion",
      ],
    },
    {
      type: "category",
      label: "API de la Consola",
      link: { type: "doc", id: "api-consola" },
      collapsed: true,
      // Páginas generadas desde apps/console-api/openapi.yaml (scripts/gen-api-docs.mjs).
      items: [{ type: "autogenerated", dirName: "referencia-api" }],
    },
    "hoja-de-ruta",
    "licencia-y-avisos",
  ],
};

export default sidebars;
