/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuario actual, roles y permisos efectivos */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resumen de la plataforma */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Overview"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catálogo de APIs */
        get: {
            parameters: {
                query?: {
                    q?: string;
                    audience?: components["schemas"]["Audience"];
                    state?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiAsset"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apis/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Ficha de una API */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiAssetDetail"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualiza metadatos de gobierno (permiso catalog:write) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ApiAssetPatch"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiAssetDetail"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        trace?: never;
    };
    "/catalog/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sincroniza el catálogo con WSO2 (APIs, suscripciones y consumidores) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SyncResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Grafo de dependencias (API → flujo → sistema → dato → consumidor) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Graph"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/impact/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simula un cambio y devuelve los activos y consumidores afectados (BT-024) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ImpactRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImpactResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discovery/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Escaneos realizados */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DiscoveryScan"][];
                    };
                };
            };
        };
        put?: never;
        /** Inicia un escaneo (permiso discovery:scan) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["DiscoveryScanRequest"];
                };
            };
            responses: {
                /** @description Aceptado */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DiscoveryScan"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discovery/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hallazgos (APIs no gobernadas) */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["FindingStatus"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DiscoveryFinding"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discovery/findings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Clasifica un hallazgo (permiso discovery:triage) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        status: components["schemas"]["FindingStatus"];
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DiscoveryFinding"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/discovery/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reporte de exposición */
        get: {
            parameters: {
                query?: {
                    format?: "json" | "csv";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anomaly-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reglas de detección */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AnomalyRule"][];
                    };
                };
            };
        };
        put?: never;
        /** Crea una regla (permiso anomaly:rules:write) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AnomalyRuleInput"];
                };
            };
            responses: {
                /** @description Creada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AnomalyRule"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anomaly-rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Modifica una regla */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AnomalyRuleInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AnomalyRule"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/anomalies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Eventos de anomalía */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["AnomalyStatus"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AnomalyEvent"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anomalies/{id}/approve-block": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aprueba el bloqueo propuesto (permiso anomaly:block:approve, cuatro ojos) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AnomalyEvent"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anomalies/{id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Descarta la anomalía (falso positivo) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Reason"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AnomalyEvent"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bloqueos activos en el gateway */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Block"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blocks/{id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Libera un bloqueo (permiso anomaly:block:release) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Reason"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Block"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rollouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Despliegues progresivos */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Rollout"][];
                    };
                };
            };
        };
        put?: never;
        /** Crea un despliegue canary o blue-green (permiso rollout:create) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RolloutInput"];
                };
            };
            responses: {
                /** @description Creado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Rollout"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rollouts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Estado del despliegue con sus pasos y métricas */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Rollout"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rollouts/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aprueba el inicio en producción (permiso rollout:approve, cuatro ojos) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Rollout"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rollouts/{id}/abort": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Detiene y revierte (permiso rollout:abort) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Reason"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Rollout"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/continuity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado de los sitios y del quórum */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ContinuityState"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/continuity/mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Cambia el modo (manual o automático) (permiso admin:settings:write) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        mode: "manual" | "automatico";
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ContinuityState"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/continuity/drill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicia un simulacro de conmutación (permiso continuity:drill) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Aceptado */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FailoverEvent"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/continuity/failback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aprueba el retorno al sitio principal (permiso continuity:failback:approve) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Reason"];
                };
            };
            responses: {
                /** @description Aceptado */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FailoverEvent"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/continuity/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historial de conmutaciones con RTO y RPO medidos */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FailoverEvent"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consumo atribuido (sin cobro) */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                    groupBy?: "consumer" | "api" | "endpoint" | "day";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UsageRow"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Exporta el consumo (CSV) */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description CSV */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dead-letters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mensajes no procesados */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeadLetter"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dead-letters/{id}/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reprocesa un mensaje (permiso dlq:reprocess:approve, auditado) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Reason"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeadLetter"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Eventos de auditoría (permiso audit:read) */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                    actor?: string;
                    action?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditEvent"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-events/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verifica la cadena de hash (permiso audit:verify) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChainVerification"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compliance/role-matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Matriz rol-permiso vigente (BT-026) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compliance/tls-channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Matriz de canales y configuración criptográfica observada (BT-028) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TlsChannel"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Genera un paquete exportado (APIs, contratos, políticas, flujos y metadatos) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Aceptado */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExportJob"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Estado y manifiesto del paquete */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExportJob"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            statusCode: number;
            message: string;
            permission?: string;
        };
        Reason: {
            reason?: string;
        };
        /** @enum {string} */
        Audience: "interna" | "operadores" | "publica";
        Me: {
            sub: string;
            name?: string;
            email?: string;
            roles: string[];
            permissions: string[];
        };
        SiteSummary: {
            /**
             * @example cpd
             * @example gcp
             */
            id: string;
            name: string;
            /** @enum {string} */
            status: "ok" | "degradado" | "caido" | "desconocido";
            active: boolean;
        };
        Overview: {
            sites?: components["schemas"]["SiteSummary"][];
            apis?: {
                total?: number;
                publicadas?: number;
                deprecadas?: number;
                completitudPromedio?: number;
            };
            alertas?: {
                abiertas?: number;
                anomalias?: number;
                hallazgos?: number;
                mensajesFallidos?: number;
            };
            consumoHoy?: {
                llamadas?: number;
                errores?: number;
                latenciaP95Ms?: number;
            };
            despliegues?: {
                enCurso?: number;
                revertidos7d?: number;
            };
        };
        ApiAsset: {
            id: string;
            wso2ApiId?: string;
            name: string;
            version: string;
            context: string;
            /** @enum {string} */
            type?: "HTTP" | "SOAP" | "GRAPHQL" | "WS" | "WEBSUB" | "SSE" | "ASYNC";
            purpose?: string;
            ownerTeam?: string;
            ownerContact?: string;
            audience: components["schemas"]["Audience"];
            /**
             * @example CREATED
             * @example PUBLISHED
             * @example DEPRECATED
             * @example RETIRED
             */
            state: string;
            authType?: string;
            /** @description repositorio@commit del contrato */
            contractRef?: string;
            /** @enum {string} */
            classification?: "publica" | "interna" | "reservada" | "datos_personales";
            consumersCount?: number;
            dependenciesCount?: number;
            completeness: number;
            /** Format: date-time */
            updatedAt?: string;
        };
        ApiAssetDetail: components["schemas"]["ApiAsset"] & {
            consumers?: {
                id?: string;
                name?: string;
                organization?: string;
                plan?: string;
                status?: string;
            }[];
            dependencies?: components["schemas"]["GraphEdge"][];
            missingFields?: string[];
            history?: {
                /** Format: date-time */
                ts?: string;
                actor?: string;
                action?: string;
                detail?: string;
            }[];
        };
        ApiAssetPatch: {
            purpose?: string;
            ownerTeam?: string;
            ownerContact?: string;
            audience?: components["schemas"]["Audience"];
            /** @enum {string} */
            classification?: "publica" | "interna" | "reservada" | "datos_personales";
            contractRef?: string;
        };
        SyncResult: {
            apis?: number;
            consumers?: number;
            subscriptions?: number;
            durationMs?: number;
        };
        GraphNode: {
            id: string;
            /** @enum {string} */
            type: "api" | "flujo" | "sistema" | "dato" | "consumidor" | "reporte";
            label: string;
            meta?: {
                [key: string]: unknown;
            };
        };
        GraphEdge: {
            from: string;
            to: string;
            /** @enum {string} */
            relation: "llama" | "lee" | "escribe" | "publica" | "transforma" | "consume";
            /** @enum {string} */
            source?: "manual" | "analizador_mi" | "trafico_observado" | "openmetadata";
        };
        Graph: {
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
        };
        ImpactRequest: {
            nodeId: string;
            change: {
                /** @enum {string} */
                kind: "contrato" | "campo" | "fuente" | "retiro";
                detail?: string;
            };
        };
        ImpactResult: {
            nodeId?: string;
            affected?: {
                consumidores?: components["schemas"]["GraphNode"][];
                apis?: components["schemas"]["GraphNode"][];
                flujos?: components["schemas"]["GraphNode"][];
                sistemas?: components["schemas"]["GraphNode"][];
                reportes?: components["schemas"]["GraphNode"][];
            };
            paths?: string[][];
            /** @enum {string} */
            severity?: "bajo" | "medio" | "alto";
        };
        DiscoveryScanRequest: {
            sources?: ("apisix" | "nginx" | "red" | "gcp")[];
            /** @description hosts o rangos autorizados */
            targets?: string[];
        };
        DiscoveryScan: {
            id: string;
            /** @enum {string} */
            status: "en_curso" | "terminado" | "fallido";
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt?: string;
            sources?: string[];
            totals?: {
                endpoints?: number;
                gobernados?: number;
                noGobernados?: number;
                riesgoAlto?: number;
            };
        };
        /** @enum {string} */
        FindingStatus: "nuevo" | "gobernado" | "riesgo_aceptado" | "en_migracion" | "descartado";
        DiscoveryFinding: {
            id: string;
            scanId?: string;
            /** @enum {string} */
            source: "apisix" | "nginx" | "red" | "gcp";
            host: string;
            port?: number;
            path: string;
            protocol?: string;
            specFound?: boolean;
            /** @enum {string} */
            authDetected?: "ninguna" | "basica" | "token" | "mtls" | "desconocida";
            tls?: string;
            personalDataSuspected?: boolean;
            matchedApiId?: string;
            exposureScore: number;
            reasons?: string[];
            status: components["schemas"]["FindingStatus"];
            /** Format: date-time */
            firstSeen?: string;
            /** Format: date-time */
            lastSeen?: string;
        };
        AnomalyRuleInput: {
            name: string;
            /** @description vacío = todas */
            apiId?: string;
            consumerId?: string;
            /** @enum {string} */
            metric: "volumen" | "errores" | "latencia" | "tamano" | "ips_distintas" | "fuera_de_horario";
            /** @description umbral en desviaciones robustas (MAD) */
            sensitivity: number;
            /** @default 30 */
            minVolume: number;
            /** @enum {string} */
            action: "alertar" | "bloquear_automatico" | "bloquear_con_aprobacion";
            /** @default 30 */
            blockTtlMinutes: number;
            /** @default true */
            enabled: boolean;
        };
        AnomalyRule: components["schemas"]["AnomalyRuleInput"] & {
            id: string;
            createdBy?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /** @enum {string} */
        AnomalyStatus: "abierta" | "bloqueo_propuesto" | "bloqueada" | "descartada" | "resuelta";
        AnomalyEvent: {
            id: string;
            /** Format: date-time */
            ts: string;
            ruleId: string;
            apiName?: string;
            consumer?: string;
            sourceIp?: string;
            metric: string;
            observed: number;
            baseline: number;
            score: number;
            actionTaken?: string;
            blockId?: string;
            status: components["schemas"]["AnomalyStatus"];
            approvedBy?: string;
        };
        Block: {
            id: string;
            denyPolicyId?: string;
            /** @enum {string} */
            conditionType: "APPLICATION" | "IP" | "USER" | "API";
            conditionValue: string;
            reason?: string;
            active: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt?: string;
            createdBy?: string;
            releasedBy?: string;
        };
        RolloutInput: {
            apiId: string;
            /** @enum {string} */
            strategy: "canary" | "blue_green";
            /** Format: uri */
            candidateEndpoint: string;
            /**
             * @default [
             *       5,
             *       25,
             *       50,
             *       100
             *     ]
             */
            steps: number[];
            /** @default 60 */
            stepDurationSec: number;
            thresholds?: {
                /**
                 * @description proporción de 0 a 1
                 * @default 0.02
                 */
                maxErrorRate: number;
                /** @default 800 */
                maxP99Ms: number;
                /** @default 20 */
                minRequests: number;
            };
            /**
             * @default prod
             * @enum {string}
             */
            environment: "dev" | "qa" | "prod";
        };
        RolloutStep: {
            weight?: number;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            endedAt?: string;
            requests?: number;
            errorRate?: number;
            p99Ms?: number;
            /** @enum {string} */
            decision?: "avanzar" | "revertir" | "pendiente";
        };
        Rollout: components["schemas"]["RolloutInput"] & {
            id: string;
            apiName?: string;
            stableEndpoint?: string;
            /** @enum {string} */
            status: "pendiente_aprobacion" | "en_curso" | "completado" | "revertido" | "abortado";
            currentWeight: number;
            stepsDone?: components["schemas"]["RolloutStep"][];
            rollbackReason?: string;
            createdBy?: string;
            approvedBy?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        SiteHealth: {
            id?: string;
            name?: string;
            /** @enum {string} */
            role?: "primario" | "respaldo" | "testigo";
            active?: boolean;
            checks?: {
                /** @enum {string} */
                gateway?: "ok" | "falla" | "desconocido";
                /** @enum {string} */
                controlPlane?: "ok" | "falla" | "desconocido";
                /** @enum {string} */
                baseDatos?: "ok" | "falla" | "desconocido";
                /** @enum {string} */
                recorridoSintetico?: "ok" | "falla" | "desconocido";
            };
            /** @enum {string} */
            vote?: "primario_sano" | "primario_caido" | "sin_voto";
            /** Format: date-time */
            lastSeen?: string;
        };
        ContinuityState: {
            /** @enum {string} */
            mode?: "manual" | "automatico";
            activeSite?: string;
            /** @description por ejemplo 2 de 3 */
            quorum?: string;
            sites?: components["schemas"]["SiteHealth"][];
            rtoObjetivoMin?: number;
            rpoObjetivoMin?: number;
        };
        FailoverEvent: {
            id?: string;
            /** @enum {string} */
            kind?: "conmutacion" | "retorno" | "simulacro";
            /** @enum {string} */
            trigger?: "automatico" | "manual" | "simulacro";
            from?: string;
            to?: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string;
            rtoSeconds?: number;
            rpoSecondsEstimated?: number;
            steps?: {
                name?: string;
                status?: string;
                /** Format: date-time */
                ts?: string;
                detail?: string;
            }[];
            /** @enum {string} */
            status?: "en_curso" | "completado" | "fallido";
            approvedBy?: string;
        };
        UsageRow: {
            key?: string;
            label?: string;
            llamadas?: number;
            errores?: number;
            bytes?: number;
            latenciaP95Ms?: number;
            plan?: string;
        };
        DeadLetter: {
            id?: string;
            queue?: string;
            flow?: string;
            error?: string;
            attempts?: number;
            /** Format: date-time */
            firstFailedAt?: string;
            /** @enum {string} */
            status?: "pendiente" | "reprocesado" | "descartado";
            reprocessedBy?: string;
            /** @description enmascarado */
            payloadPreview?: string;
        };
        AuditEvent: {
            id?: string;
            seq?: number;
            /** Format: date-time */
            ts?: string;
            source?: string;
            actor?: string;
            actorType?: string;
            action?: string;
            resource?: string;
            result?: string;
            sourceIp?: string;
            correlationId?: string;
            prevHash?: string;
            hash?: string;
        };
        ChainVerification: {
            ok?: boolean;
            count?: number;
            lastSeq?: number;
            brokenAt?: number;
            reason?: string;
        };
        TlsChannel: {
            canal?: string;
            origen?: string;
            destino?: string;
            protocolo?: string;
            versiones?: string[];
            cifrado?: string;
            /** Format: date-time */
            verificado?: string;
        };
        ExportJob: {
            id?: string;
            /** @enum {string} */
            status?: "en_curso" | "listo" | "fallido";
            /** Format: date-time */
            createdAt?: string;
            manifest?: {
                version?: string;
                items?: {
                    tipo?: string;
                    nombre?: string;
                    archivo?: string;
                    sha256?: string;
                }[];
            };
            downloadUrl?: string;
        };
    };
    responses: {
        /** @description No existe */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Sin permiso */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Id: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
